name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clone Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: Create Android Folder
        run: flutter create . --platforms=android --org com.example

      - name: Fix JCenter Deprecation in Dependencies
        run: |
          find ~/.pub-cache -name "build.gradle" -type f -exec sed -i 's/jcenter()/mavenCentral()/g' {} + || true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --no-pub

      - name: Upload Artifact APK
        uses: actions/upload-artifact@v4
        with:
          name: RB-AI-Agent-APK
          path: build/app/outputs/flutter-apk/app-release.apk
